sudo: false
language: go
go: 
    - master
git:
    depth: 1
install:
    - wget -q -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.76.5/hugo_extended_0.76.5_Linux-64bit.deb
    - sudo dpkg -i hugo.deb
script: hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $token
    on:
        branch: master
    local_dir: public
    repo: pureboys/pureboys.github.io
    target_branch: master
    email: yuyuud@gmail.com
    name: pureboy