sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script: hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $token
    on:
        branch: master
    local_dir: public
    repo: pureboys/pureboys.github.io
    target_branch: master
    email: yuyuud@gmail.com
    name: pureboy